FROM python:3.8.13-slim-bullseye

RUN mkdir /cache
RUN mkdir /agent
COPY requirements.txt /agent/
COPY entrypoint.sh /agent/
RUN chmod +x /agent/entrypoint.sh
WORKDIR /agent
RUN pip3 install -r requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:/agent/cluster_agent"
