FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y
RUN apt install -y slurm-wlm mariadb-server
# munge

COPY slurm.conf /etc/slurm-llnl/
COPY cgroup.conf /etc/slurm-llnl/
COPY master-entrypoint.sh /etc/slurm-llnl/entrypoint.sh
RUN chmod +x /etc/slurm-llnl/entrypoint.sh

VOLUME /agent

EXPOSE 6817 6818 6819 6820 3306

ENTRYPOINT ["/etc/slurm-llnl/entrypoint.sh"]
