FROM ubuntu:21.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y
RUN apt install -y slurm-wlm slurmrestd slurmdbd mariadb-server
# munge

COPY cgroup.conf /etc/slurm/
COPY slurm.conf /etc/slurm/
COPY slurmdbd.conf /etc/slurm/
RUN chmod 600 /etc/slurm/slurmdbd.conf

COPY master-entrypoint.sh /etc/slurm/entrypoint.sh
RUN chmod +x /etc/slurm/entrypoint.sh

VOLUME /agent

EXPOSE 6817 6818 6819 6820 3306
