name: 'Publish Release'

on:
  workflow_dispatch:
    inputs:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: "Upload the artifact"
    steps:
      - uses: actions/checkout@v2

      - name: "Parse and store the release_version"
        id: vars
        shell: bash
        run: |
          echo "::set-output name=release_version::$(echo $(git branch | grep '*' | awk '{print$2}') | sed 's/[a-z-]*\///g')"
      - id: set-env
        if: ${{ success() }}
        run: |
          echo 'RELEASE_VERSION=${{ steps.vars.outputs.release_version }}' >> $GITHUB_ENV;
      - id: set-git-user
        run: |
          git config user.name omnivector-qa
          git config user.email admin@omnivector.solutions
      - uses: getsentry/craft@master
        if: ${{ success() }}
        name: "Craft Publish"
        with:
          action: publish
          version: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CRAFT_LOG_LEVEL: debug

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Publish to pypicloud
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.5
      - run: |
          source $HOME/.poetry/env

          poetry build

          poetry config repositories.pypicloud ${{ secrets.PYPI_URL }}

          poetry publish \
              --repository pypicloud \
              --username ${{ secrets.PYPI_USERNAME }} \
              --password ${{ secrets.PYPI_PASSWORD }}

      - id: next-dev-version
        if: ${{ success() }}
        run: |
          git fetch --all
          git checkout main
          NEXT="$(echo ${{env.RELEASE_VERSION}} | awk -F. -v OFS=. '{$NF++;print}')-dev0"
          ./.craft/bump-version.sh '' $NEXT
          git diff --quiet || git commit -anm 'meta: Bump new development version' && git pull --rebase && git push