name: Create Release
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish cluster-agent

    runs-on: ubuntu-latest

    steps:

      - name: Fail if ref is not a tag
        if: github.ref_type != 'tag'
        run: |
          echo "Publish only supported from tag refs!"
          echo "Got ref_type=${{ github.ref_type }} instead"
          exit 1

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install twine
        run: |
          pip3 install -U pip wheel twine

      - name: Build package
        run: |
          python3 setup.py sdist bdist_wheel

      - name: Publish to codeartifact
        run: |
          twine upload -u __token__ -p ${{ secrets.OMNIVECTOR_PYPI_TOKEN }} dist/* --verbose
