name: 'Test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - test-development

jobs:
  test:
    name: "Test code and check lint"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make dependencies

      - name: "tests"
        run: |
          make test

      - name: "lint"
        run: |
          make lint